Netflix/Models/Genere.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Netflix.Models
{
    public class Genere : BaseModel
    {
        [Required]
        [MinLength(2)]
        [DisplayName("Genre Name")]
        public string Name { get; set; }

        public virtual ICollection<Movie> Movies { get; set; }

    }
}

Netflix/Controllers/GeneresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Netflix.Data;
using Netflix.Models;

namespace Netflix.Controllers
{
    [Authorize]
    public class GeneresController : Controller
    {
        private readonly NetflixContext _context;

        public GeneresController(NetflixContext context)
        {
            _context = context;
        }

        // GET: Generes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Genere.ToListAsync());
        }

        // GET: Generes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genere = await _context.Genere
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genere == null)
            {
                return NotFound();
            }

            return View(genere);
        }

        // GET: Generes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Generes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Id")] Genere genere)
        {
            if (ModelState.IsValid)
            {
                if (_context.Genere.Any(x => x.Name == genere.Name))
                {
                    ViewBag.Message = "Already exist";
                }
                else
                {
                    _context.Add(genere);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }

            return View(genere);
        }

        // GET: Generes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genere = await _context.Genere.FindAsync(id);
            if (genere == null)
            {
                return NotFound();
            }

            return View(genere);
        }

        // POST: Generes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Id")] Genere genere)
        {
            if (id != genere.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (_context.Genere.Any(x => x.Name == genere.Name))
                {
                    ViewBag.Message = "Already exist";
                }
                else
                {
                    try
                    {
                        _context.Update(genere);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!GenereExists(genere.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(genere);
        }

        // GET: Generes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genere = await _context.Genere
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genere == null)
            {
                return NotFound();
            }

            return View(genere);
        }

        // POST: Generes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var genere = await _context.Genere.FindAsync(id);
            _context.Genere.Remove(genere);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GenereExists(int id)
        {
            return _context.Genere.Any(e => e.Id == id);
        }

        [HttpGet]
        public ActionResult Search(string name)
        {
            return View(_context.Genere
                .Where(genere =>
                    (!string.IsNullOrEmpty(name) && genere.Name.ToLower().Contains(name.ToLower()))).ToList());
        }
    }
}

Netflix/Views/Generes/Create.cshtml
@model Netflix.Models.Genere

@{
    ViewData["Title"] = "Create";
}

<h1>Create genre</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>

                @if (@ViewBag.Message != null)
                {
                    <div class="text-danger"> @ViewBag.Message</div>
                }
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<a asp-action="Index" class="btn btn-primary">Back to List</a>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Netflix/Views/Generes/Delete.cshtml
@model Netflix.Models.Genere

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this genere?</h3>
<h5>(All Movies and reviews related to the genere will be deleted as well)</h5>
<div>
    <hr />
    <dl class="row">
        @*<dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>*@
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-primary" />
        <br>
        <a asp-action="Index" class="btn btn-primary">Back to List</a>
    </form>
</div>

Netflix/Views/Generes/Details.cshtml
@model Netflix.Models.Genere

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a> |
    <a asp-action="Index" class = "btn btn-primary">Back to List</a>
</div>

Netflix/Views/Generes/Edit.cshtml
@model Netflix.Models.Genere

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Genere</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
              
                @if (@ViewBag.Message != null)
                {
                    <div class="text-danger"> @ViewBag.Message</div>
                }

            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class = "btn btn-primary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Netflix/Views/Generes/Index.cshtml
@model IEnumerable<Netflix.Models.Genere>

@{
    ViewData["Title"] = "Index";
}

@using (Html.BeginForm("Search", "Generes", FormMethod.Get))
    {
        <div class="d-flex flex-row align-items-center">
  <div class="p-2">
  <h1>Genres</h1>
  </div>
        <div class="p-2 justify-content-end main-search">
            <div style="width: 35%;">
                <div class="input-group">
                    <input type="text" class="form-control" name="name" placeholder="Search genre by name...">
                    <span class="input-group-btn">
                        <button class="btn btn-primary" type="submit">Search!</button>
                    </span>
                </div>
            </div>
        </div>
</div>
    }
        <p>
            <a asp-action="Create" class="btn btn-primary">Add a new Genre</a>
        </p>
<br />

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class = "btn btn-primary">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id" class = "btn btn-primary">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" class = "btn btn-primary">Delete</a>
                  </td>
            </tr>
        }
    </tbody>
</table>

Netflix/Views/Generes/Search.cshtml
@{
    ViewBag.Title = "Search";
}

@using Netflix.Models
@model IEnumerable<Genere>

@{
    ViewBag.Title = "Search Results";
    //var user = (User)Session["User"];
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
        </tr>
    }

</table>